name: meshsightapp
description: "MeshSight APP"
publish_to: "none"
version: 0.4.0+240824350
environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: 8.1.3
  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  global_configuration: ^2.0.0
  intl_utils: ^2.8.7
  logging_flutter: ^3.0.0
  package_info_plus: ^8.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  device_info_plus: ^10.1.2
  archive: ^3.6.1
  path: ^1.9.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  loading_animation_widget: ^1.2.1
  uuid: ^4.4.2
  http: ^1.2.2
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.0
  getwidget: ^4.0.0
  latlong2: ^0.9.1
  auto_size_text: ^3.0.0
  particles_fly: ^0.0.9
  fl_chart: ^0.68.0
dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cfg/
    - assets/images/meshtastic/device/
flutter_intl:
  enabled: true
  arb_dir: lib/localization/l10n
  output_dir: lib/localization/generated
  use_deferred_loading: false
