name: meshsightapp
description: "MeshSight APP"
publish_to: "none"
version: 0.8.0+250729101
environment:
  sdk: ">=3.8.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^10.1.0
  cupertino_icons: ^1.0.0
  get_it: ^8.2.0
  global_configuration: ^2.0.0
  intl_utils: ^2.8.0
  logging_flutter: ^3.0.0
  package_info_plus: ^9.0.0
  provider: ^6.1.0
  shared_preferences: ^2.5.0
  sqflite: ^2.4.0
  path_provider: ^2.1.0
  device_info_plus: ^12.1.0
  archive: ^4.0.0
  path: ^1.9.0
  intl: ^0.20.0
  flutter_svg: ^2.2.0
  loading_animation_widget: ^1.3.0
  uuid: ^4.5.0
  http: ^1.5.0
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.0
  geolocator: ^14.0.0
  url_launcher: ^6.3.0
  getwidget: ^7.0.0
  latlong2: ^0.9.0
  auto_size_text: ^3.0.0
  fl_chart: ^0.68.0
  flutter_map_marker_cluster_2: ^1.0.4
  font_awesome_flutter: ^10.7.0
dev_dependencies:
  auto_route_generator: ^10.2.0
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cfg/
    - assets/images/
    - assets/images/meshtastic/device/
flutter_intl:
  enabled: true
  arb_dir: lib/localization/l10n
  output_dir: lib/localization/generated
  use_deferred_loading: false
